platform :ios, '9.0'

target 'BarsAroundMe' do
    use_frameworks!

    pod 'SwiftyJSON'
    pod 'RxSwift',    '~> 3.0'
    pod 'RxCocoa',    '~> 3.0'

    target 'BarsAroundMeTests' do
        inherit! :search_paths
        # Pods for testing
        pod 'Quick', '~> 1.0'
        pod 'Nimble', '~> 6.0'
        pod 'Mockingjay', '~> 2.0'
    end

end
