platform :ios, '9.0'

target 'BarsAroundMe' do
    use_frameworks!

    target 'BarsAroundMeTests' do
        inherit! :search_paths
        # Pods for testing
        pod 'Quick', '~> 1.0'
        pod 'Nimble', '~> 6.0'
    end

end

